version: "3.6"

services:
  server:
    build: ui_server
    environment:
      MARIADB_HOST: database_mariadb
      MARIADB_USER: mysqluser
      MARIADB_PASSWORD: mysqlpassword
      MARIADB_DBNAME: stocks
      MARIADB_PORT: 3306
    ports:
    - 5050:5000
    expose:
    - 5050
    networks:
    - fintech
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  mongodata:

networks:
  fintech:
