version: "3.6"

services:
  nginx:
    build: nginx
    networks:
    - fintech
    ports:
    - 8089:80

  # finviz:
  #   build: server_finviz
  #   networks:
  #   - fintech
  #   ports:
  #   - 8085:8080
  #
  # mongodb:
  #   image: mongo:latest
  #   networks:
  #   - fintech
  #   volumes:
  #   - mongodata:/data/db
  #   ports:
  #   - 27027:27017
  #   expose:
  #   - 27027
  #   environment:
  #     MONGODB_USERNAME: mongoadmin
  #     MONGODB_PASSWORD: secret
  #     MONGODB_DATABASE: stocks
  #
  # database_mariadb:
  #   image: mariadb
  #   environment:
  #     MYSQL_DATABASE: stocks
  #     MYSQL_USER: mysqluser
  #     MYSQL_PASSWORD: mysqlpassword
  #     MYSQL_ROOT_PASSWORD: myrootpassword
  #   networks:
  #   - fintech
  #   ports:
  #   - 3406:3306

volumes:
  mongodata:

networks:
  fintech:
